config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }

  root 'home#index'
  get '/profile', as: :user_root, controller: :profile, action: :show
  resources :users do
    member do
      resources :tasks, only: [:index]
    end
  end

  resources :tasks, only: [:show, :new, :create, :edit, :update, :destroy] do
    collection do
      get '/search', controller: :tasks, action: :search
    end
  end
end

app/models/application_record.rb
# frozen_string_literal: true

# Base class for models
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
# frozen_string_literal: true

# Model for persist task's data
class Task < ApplicationRecord
  include AASM

  validates :name, presence: true
  belongs_to :creator, class_name: 'User'
  belongs_to :assignee, class_name: 'User'

  aasm :state do
    state :new, initial: true
    state :started
    state :finished

    event :start do
      transitions from: :new, to: :started
    end

    event :finish do
      transitions from: :started, to: :finished
    end

    event :reopen do
      transitions from: :finished, to: :new
    end
  end

  def self.states
    aasm(:state).states.map(&:name)
  end
end

app/models/user.rb
# frozen_string_literal: true

# Model for persist user's data
class User < ApplicationRecord
  devise :database_authenticatable,
         :registerable,
         :lockable,
         :recoverable,
         :rememberable,
         :trackable,
         :validatable

  has_many :created_tasks,
           foreign_key: :creator_id,
           class_name: 'Task',
           dependent: :restrict_with_exception,
           inverse_of: false
  has_many :assigned_tasks,
           foreign_key: :assignee_id,
           class_name: 'Task',
           dependent: :restrict_with_exception,
           inverse_of: false

  validates :name, presence: true
end

app/controllers/application_controller.rb
# frozen_string_literal: true

# Base controller
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
# frozen_string_literal: true

# Root controller
class HomeController < ApplicationController
  def index
    redirect_to user_root_path if user_signed_in?
  end
end

app/controllers/profile_controller.rb
# frozen_string_literal: true

# Controller for user's profile. Accessed only for authenticated users
class ProfileController < ApplicationController
  before_action :authenticate_user!

  def show
    @user = current_user
  end
end

app/controllers/registrations_controller.rb
# frozen_string_literal: true

# Class for getting additional params when creat and update user
class RegistrationsController < Devise::RegistrationsController
  private

  def sign_up_params
    params.require(:user).permit(:name, :email, :password,
                                 :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:name, :email, :password,
                                 :password_confirmation, :current_password)
  end
end

app/controllers/tasks_controller.rb
# frozen_string_literal: true

# Controller for creating and updating tasks
class TasksController < ApplicationController
  def search
    tasks = ::Tasks::SearchQuery.new(params[:query]).result

    render :search, locals: { tasks: tasks, caption: 'Search result' }
  end

  def new
    task = Task.new

    render :new, locals: { task: task }
  end

  def create
    result = ::Tasks::Create.call(task_params)

    if result.success?
      flash[:alert] = 'Task was created successfully'
      redirect_to user_root_path
    else
      flash[:danger] = result.error
      render :new, locals: { task: result.task }, status: :conflict
    end
  end

  def edit
    task = Task.find(params[:id])

    render :edit, locals: { task: task }
  end

  def update
    result = ::Tasks::Update.call(task_params.merge(id: params[:id]))

    if result.success?
      flash[:alert] = 'Task was updated successfully'
      redirect_to user_root_path
    else
      flash[:danger] = result.error
      render :edit, locals: { task: result.task }, status: :conflict
    end
  end

  def destroy
    task = Task.find(params[:id])

    if task.destroy
      flash[:alert] = 'Task was destroyed successfully'
      redirect_to user_root_path
    else
      flash[:danger] = task.errors.full_messages
      render :edit, locals: { task: task }, status: :conflict
    end
  end

  private

  def task_params
    params.require(:task).permit(:name, :description, :creator_id,
                                 :assignee_id, :state)
  end
end

app/views/home/index.html.slim
.container
  .row
    .col.align-self-center
      .jumbotron
        h1.display-4 TaskYouself
        p.lead Simple tool for create and do tasks
        hr.my-4
        p.lead
          = link_to 'Sign in', new_user_session_url, class: 'btn btn-primary btn-lg', role: 'button'

app/views/layouts/application.html.slim
doctype html
html
  head
    title TaskYourself
    = csrf_meta_tags
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    - if notice.present?
      p.alert.alert-success= notice
    - if alert.present?
      p.alert.alert-warning= alert
    - if signed_in?
      = render partial: 'shared/navbar'
    main
      .container.mt-5.mb-5
        = yield

app/views/shared/_navbar.html.slim
header
  .navbar.navbar-expand-lg.navbar-dark.bg-primary
    = link_to 'TaskYourself', root_path, class: 'navbar-brand'
    = link_to 'Create task', new_task_path, class: 'btn btn-outline-light mr-auto'
    = form_tag(search_tasks_path, method: :get, class: 'form-inline') do
      = text_field_tag :query, '', placeholder: 'Search tasks', class: 'form-control mr-sm-2'
      = button_tag name: nil, type: :submit, class: 'btn btn-outline-light my-2 my-sm-0' do
        = fa_icon 'search'
    ul.navbar-nav
      li.nav-item
        = link_to "Logged as #{current_user.email}", user_root_path, class: 'nav-link'
      li.nav-item
        = link_to 'Sign out', destroy_user_session_path, method: :delete, class: 'nav-link'

app/views/shared/_tasks_table.html.slim
table.table.table-striped
  caption= caption
  thead
    tr
      th scope='col' ID
      th scope='col' Name
      th scope='col' Description
      th scope='col' Creator
      th scope='col' State
      th scope='col' Edit
      th scope='col' Destroy
  tbody
    - tasks.each do |task|
      tr
        td scope='row'= task.id
        td= task.name
        td= task.description
        td= task.creator.name
        td= task.state
        td= link_to edit_task_path(task) do
              = fa_icon 'edit'
        td= link_to task_path(task), method: :delete do
          = fa_icon 'times'

app/views/tasks/_form.html.slim
- creator_option = task.creator.present? ? [[task.creator.name, task.creator_id]] : [[current_user.name, current_user.id]]
- assignee_options = task.assignee.present? ? [[task.assignee.name, task.assignee_id]] : options_from_collection_for_select(User.all, :id, :name)
- state_options = Task.states.map { |state| [state, state] }
.container.mt-5
  = form_for task, url: { action: action } do |f|
    .form-group
      = f.label :name, 'Task name'
      = f.text_field :name, class: 'form-control'
    .form-group
      = f.label :description, 'Task description'
      = f.text_field :description, class: 'form-control'
    .form-group
      = f.label :creator_id, 'Task creator'
      = f.select :creator_id, creator_option, {},
        class: 'form-control custom-select'
    .form-group
      = f.label :assignee_id, 'Task assignee'
      = f.select :assignee_id, assignee_options,
        { include_blank: 'Select assignee' }, class: 'form-control custom-select'
    - if action == :update
      .form-group
        = f.label :state, 'Task state'
        = f.select :state, state_options, {}, class: 'form-control custom-select'
    = f.submit submit_text, class: 'btn btn-primary'

app/views/tasks/edit.html.slim
= render partial: 'form', locals: { task: task, action: :update, submit_text: 'Update' }

app/views/tasks/new.html.slim
= render partial: 'form', locals: { task: task, action: :create, submit_text: 'Create' }

app/views/tasks/search.html.slim
= render partial: 'shared/tasks_table', locals: { tasks: tasks, caption: 'Search result' }

app/views/users/shared/_links.html.slim
- if controller_name != 'sessions'
  = link_to "Log in", new_session_path(resource_name)
  br
- if devise_mapping.registerable? && controller_name != 'registrations'
  = link_to "Sign up", new_registration_path(resource_name)
  br
- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations'
  = link_to "Forgot your password?", new_password_path(resource_name)
  br
- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks'
  = link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name)
  br